owner: paulkiernan
repo: paulynomial-uptime

sites:
  - name: Paulynomial (index)
    url: https://paulynomial.com
  - name: Hack the Gibson
    url: https://gibson.paulynomial.com
  - name: Taqueria Bonjour (frontend)
    url: https://bonjour.paulynomial.com
  - name: Taqueria Bonjour (backend)
    url: https://bonjour.paulynomial.com/api/team
  - name: Paulynomial (index) (www-redirect)
    url: https://www.paulynomial.com
  - name: Paulynomial (index) (paulinomial-redirect)
    url: https://paulinomial.com
  - name: Paulynomial (index) (www-paulinomial-redirect)
    url: https://www.paulinomial.com
  - name: Paulynomial (index) (paul-kiernan-redirect)
    url: https://paul-kiernan.com
  - name: Paulynomial (index) (www-paul-kiernan-redirect)
    url: https://www.paul-kiernan.com

assignees:
  - paulkiernan

status-website:
  baseUrl: /paulynomial-uptime
  name: Paulynomial Uptime
